### ISSUE TITLE
Mising dependencies errors

### ISSUE THREAD

**Issue by thanoue** [drasticactions/Drastic.LeakCanary#1]
I'm testing your library on my .Net Android project (.net 7).
But it raise the "Heap analysis failed" error: Didn't find class "okio.Okio" 
Please let me know what it was missing. what can I do to fix it? 

=====================
this is the log trace
ava.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
at shark.ThrowingCancelableFileSourceProvider.openStreamingSource(ThrowingCancelableFileSourceProvider.kt:20)
at shark.ConstantMemoryMetricsDualSourceProvider.openStreamingSource(ConstantMemoryMetricsDualSourceProvider.kt:48)
at shark.HprofHeapGraph$Companion.openHeapGraph(HprofHeapGraph.kt:427)
at shark.HprofHeapGraph$Companion.openHeapGraph$default(HprofHeapGraph.kt:425)
at leakcanary.internal.AndroidDebugHeapAnalyzer.analyzeHeap(AndroidDebugHeapAnalyzer.kt:145)
at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking(AndroidDebugHeapAnalyzer.kt:59)
at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking$default(AndroidDebugHeapAnalyzer.kt:46)
at [leakcanary.BackgroundThreadHeapAnalyzer$onEvent$1.run](http://leakcanary.backgroundthreadheapanalyzer%24onevent%241.run/)(BackgroundThreadHeapAnalyzer.kt:24)
at android.os.Handler.handleCallback([Handler.java:883](http://handler.java:883/))
at android.os.Handler.dispatchMessage([Handler.java:100](http://handler.java:100/))
at android.os.Looper.loop([Looper.java:224](http://looper.java:224/))
at [android.os.HandlerThread.run](http://android.os.handlerthread.run/)([HandlerThread.java:67](http://handlerthread.java:67/))
Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Okio" on path: DexPathList[[zip file "/data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/lib/arm, /data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
at dalvik.system.BaseDexClassLoader.findClass([BaseDexClassLoader.java:230](http://basedexclassloader.java:230/))
at java.lang.ClassLoader.loadClass([ClassLoader.java:379](http://classloader.java:379/))
at java.lang.ClassLoader.loadClass([ClassLoader.java:312](http://classloader.java:312/))
... 12 more

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.10
Analysis duration: 0 ms
Heap dump file path: /data/user/0/com.xcr.payapp/cache/leakcanary/2023-06-05_10-49-31_428.hprof
Heap dump timestamp: 1685936974209
=====================

Thanks.

**Comment by thanoue** [comment]
this is the log trace
ava.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
	at shark.ThrowingCancelableFileSourceProvider.openStreamingSource(ThrowingCancelableFileSourceProvider.kt:20)
	at shark.ConstantMemoryMetricsDualSourceProvider.openStreamingSource(ConstantMemoryMetricsDualSourceProvider.kt:48)
	at shark.HprofHeapGraph$Companion.openHeapGraph(HprofHeapGraph.kt:427)
	at shark.HprofHeapGraph$Companion.openHeapGraph$default(HprofHeapGraph.kt:425)
	at leakcanary.internal.AndroidDebugHeapAnalyzer.analyzeHeap(AndroidDebugHeapAnalyzer.kt:145)
	at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking(AndroidDebugHeapAnalyzer.kt:59)
	at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking$default(AndroidDebugHeapAnalyzer.kt:46)
	at [leakcanary.BackgroundThreadHeapAnalyzer$onEvent$1.run](http://leakcanary.backgroundthreadheapanalyzer%24onevent%241.run/)(BackgroundThreadHeapAnalyzer.kt:24)
	at android.os.Handler.handleCallback([Handler.java:883](http://handler.java:883/))
	at android.os.Handler.dispatchMessage([Handler.java:100](http://handler.java:100/))
	at android.os.Looper.loop([Looper.java:224](http://looper.java:224/))
	at [android.os.HandlerThread.run](http://android.os.handlerthread.run/)([HandlerThread.java:67](http://handlerthread.java:67/))
Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Okio" on path: DexPathList[[zip file "/data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/base.apk"],nativeLibraryDirectories=[/data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/lib/arm, /data/app/com.xcr.payapp-ibpckSkKoF9B3539KuM4ig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
	at dalvik.system.BaseDexClassLoader.findClass([BaseDexClassLoader.java:230](http://basedexclassloader.java:230/))
	at java.lang.ClassLoader.loadClass([ClassLoader.java:379](http://classloader.java:379/))
	at java.lang.ClassLoader.loadClass([ClassLoader.java:312](http://classloader.java:312/))
	... 12 more

Build.VERSION.SDK_INT: 29
Build.MANUFACTURER: Xiaomi
LeakCanary version: 2.10
Analysis duration: 0 ms
Heap dump file path: /data/user/0/com.xcr.payapp/cache/leakcanary/2023-06-05_10-49-31_428.hprof
Heap dump timestamp: 1685936974209

**Comment by db2222** [comment]
At least for me it worked when I add the [NuGet package](https://www.nuget.org/packages/Square.OkIO/2.2.2) `Square.OkIO` with version `2.2.2` to my project that uses `Drastic.LeakCanary`. The problem seems to be that `Drastic.LeakCanary` references the wrong compatible version `3.3.0`.
