### ISSUE TITLE
Heap analysis failed-Failed resolution of: Lokio/Okio

### ISSUE THREAD

**Issue by BaY1251** [drasticactions/Drastic.LeakCanary#3]
01-22 09:15:44.807 25945 26015 D LeakCanary: Found 5 objects retained, dumping heap now (app is visible & >=5 threshold)
01-22 09:15:44.816 25945 26015 D LeakCanary: Removing 1 heap dumps
01-22 09:15:44.987 25945 25945 D LeakCanary: Watching instance of crc640ec207abc449b2ca.ShellPageContainer (crc640ec207abc449b2ca.ShellFragmentContainer received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 5b5e2dd9-ceb8-4a9e-b3e9-dfdc8b4a142e
01-22 09:15:44.987 25945 25945 D LeakCanary: Watching instance of androidx.coordinatorlayout.widget.CoordinatorLayout (crc640ec207abc449b2ca.ShellSectionRenderer received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key aebf84fe-c1e4-4874-84b9-2de3afd6878e
01-22 09:15:44.988 25945 25945 D LeakCanary: Watching instance of android.widget.LinearLayout (crc640ec207abc449b2ca.ShellItemRenderer received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key 25daa089-15dc-4f17-b3bc-e2093e09856c
01-22 09:15:44.989 25945 25945 D LeakCanary: Watching instance of crc640ec207abc449b2ca.ShellFragmentContainer (crc640ec207abc449b2ca.ShellFragmentContainer received Fragment#onDestroy() callback) with key 40e613ee-e755-4a07-a8a2-91564bfae337
01-22 09:15:44.995 25945 25945 D LeakCanary: Watching instance of crc640ec207abc449b2ca.ShellSectionRenderer (crc640ec207abc449b2ca.ShellSectionRenderer received Fragment#onDestroy() callback) with key 0b5695ad-f3bc-47e1-a9dd-ec642e9706e3
01-22 09:15:44.997 25945 25945 D LeakCanary: Watching instance of crc640ec207abc449b2ca.ShellItemRenderer (crc640ec207abc449b2ca.ShellItemRenderer received Fragment#onDestroy() callback) with key c9f8f0f8-c873-4d60-bec8-1aaba9ca63ae
01-22 09:15:45.004 25945 25950 I art     : Do partial code cache collection, code=124KB, data=118KB
01-22 09:15:45.005 25945 25950 I art     : After code cache collection, code=124KB, data=118KB
01-22 09:15:45.005 25945 25950 I art     : Increasing code cache capacity to 512KB
01-22 09:15:45.162 25945 26016 D mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
01-22 09:15:45.549 25945 26015 W ResourceType: For resource 0x7f080237, entry index(567) is beyond type entryCount(567)
01-22 09:15:45.576 25945 26015 I art     : hprof: heap dump "/storage/emulated/0/Download/leakcanary-com.ainuo.magic/2024-01-22_09-15-44_841.hprof" starting...
01-22 09:15:47.183 25945 26015 I art     : hprof: heap dump completed (24MB) in 1.607s objects 292792 objects with stack traces 0
01-22 09:15:47.269 25945 26036 D LeakCanary: Analysis in progress, 0% done, working on Parsing heap dump
01-22 09:15:47.274 25945 26036 D LeakCanary: Analysis in progress, 90% done, working on Reporting heap analysis
01-22 09:15:47.277   570  1636 I NotificationService: cancelToast pkg=com.ainuo.magic callback=android.app.ITransientNotification$Stub$Proxy@f418ab3
01-22 09:15:47.277   570  1636 W WindowManager: Attempted to remove non-existing token: android.os.Binder@98f8658
01-22 09:15:47.279 25945 25945 D LeakCanary: Watching instance of android.widget.FrameLayout (android.widget.FrameLayout received View#onDetachedFromWindow() callback) with key 6eb4aeb1-39cd-43d6-a4d2-1e4c1022c373
01-22 09:15:47.333 25945 25964 D LeakCanary: Setting up flushing for Thread[HeapAnalyzer,5,main]
01-22 09:15:47.336 25945 26036 D LeakCanary: ​
01-22 09:15:47.336 25945 26036 D LeakCanary: ====================================
01-22 09:15:47.336 25945 26036 D LeakCanary: HEAP ANALYSIS FAILED
01-22 09:15:47.336 25945 26036 D LeakCanary: 
01-22 09:15:47.336 25945 26036 D LeakCanary: You can report this failure at https://github.com/square/leakcanary/issues
01-22 09:15:47.336 25945 26036 D LeakCanary: Please provide the stacktrace, metadata and the heap dump file.
01-22 09:15:47.336 25945 26036 D LeakCanary: ====================================
01-22 09:15:47.336 25945 26036 D LeakCanary: STACKTRACE
01-22 09:15:47.336 25945 26036 D LeakCanary: 
01-22 09:15:47.336 25945 26036 D LeakCanary: java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Okio;
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at shark.ThrowingCancelableFileSourceProvider.openStreamingSource(ThrowingCancelableFileSourceProvider.kt:20)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at shark.ConstantMemoryMetricsDualSourceProvider.openStreamingSource(ConstantMemoryMetricsDualSourceProvider.kt:48)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at shark.HprofHeapGraph$Companion.openHeapGraph(HprofHeapGraph.kt:427)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at shark.HprofHeapGraph$Companion.openHeapGraph$default(HprofHeapGraph.kt:425)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at leakcanary.internal.AndroidDebugHeapAnalyzer.analyzeHeap(AndroidDebugHeapAnalyzer.kt:145)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking(AndroidDebugHeapAnalyzer.kt:59)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at leakcanary.internal.AndroidDebugHeapAnalyzer.runAnalysisBlocking$default(AndroidDebugHeapAnalyzer.kt:46)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at leakcanary.BackgroundThreadHeapAnalyzer$onEvent$1.run(BackgroundThreadHeapAnalyzer.kt:24)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at android.os.Handler.handleCallback(Handler.java:755)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at android.os.Looper.loop(Looper.java:154)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at android.os.HandlerThread.run(HandlerThread.java:61)
01-22 09:15:47.336 25945 26036 D LeakCanary: Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Okio" on path: DexPathList[[zip file
01-22 09:15:47.336 25945 26036 D LeakCanary: "/data/app/com.ainuo.magic-1/base.apk"],nativeLibraryDirectories=[/data/app/com.ainuo.magic-1/lib/arm64, /data/app/com.
01-22 09:15:47.336 25945 26036 D LeakCanary: ainuo.magic-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-22 09:15:47.336 25945 26036 D LeakCanary: 	... 12 more
01-22 09:15:47.336 25945 26036 D LeakCanary: ====================================
01-22 09:15:47.336 25945 26036 D LeakCanary: METADATA
01-22 09:15:47.336 25945 26036 D LeakCanary: 
01-22 09:15:47.336 25945 26036 D LeakCanary: Build.VERSION.SDK_INT: 25
01-22 09:15:47.336 25945 26036 D LeakCanary: Build.MANUFACTURER: rockchip
01-22 09:15:47.336 25945 26036 D LeakCanary: LeakCanary version: 2.10
01-22 09:15:47.336 25945 26036 D LeakCanary: Analysis duration: 0 ms
01-22 09:15:47.336 25945 26036 D LeakCanary: Heap dump file path: /storage/emulated/0/Download/leakcanary-com.ainuo.magic/2024-01-22_09-15-44_841.hprof
01-22 09:15:47.336 25945 26036 D LeakCanary: Heap dump timestamp: 1705886147274
01-22 09:15:47.336 25945 26036 D LeakCanary: ====================================

[2024-01-17_08-54-56_136.zip](https://github.com/drasticactions/Drastic.LeakCanary/files/14003897/2024-01-17_08-54-56_136.zip)

**Comment by b12kab** [comment]
I get this as well.

**Comment by db2222** [comment]
At least for me it worked when I add the [NuGet package](https://www.nuget.org/packages/Square.OkIO/2.2.2) `Square.OkIO` with version `2.2.2` to my project that uses `Drastic.LeakCanary`. The problem seems to be that `Drastic.LeakCanary` references the wrong compatible version `3.3.0`.
